# Generated by Django 3.1 on 2020-08-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20200825_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment_name',
            field=models.CharField(default='', help_text='The name of the coding assignment this is a submission for', max_length=256),
        ),
    ]
