# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='applicant_address',
            field=models.EmailField(help_text="Applicant's contact email address", max_length=2048),
        ),
    ]
